export const langColor: Record<string, { bg: string; text: string }> = {
  Python:     { bg: 'bg-yellow-100/80 dark:bg-yellow-900/30', text: 'text-yellow-700 dark:text-yellow-400' },
  TypeScript: { bg: 'bg-blue-100/80 dark:bg-blue-900/30',   text: 'text-blue-700 dark:text-blue-400' },
  JavaScript: { bg: 'bg-amber-100/80 dark:bg-amber-900/30', text: 'text-amber-700 dark:text-amber-400' },
  'C#':       { bg: 'bg-indigo-100/80 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-400' },
  Dart:       { bg: 'bg-cyan-100/80 dark:bg-cyan-900/30',   text: 'text-cyan-700 dark:text-cyan-400' },
  default:    { bg: 'bg-slate-100/80 dark:bg-slate-800/50', text: 'text-slate-600 dark:text-slate-400' },
};

export const ALL_COLLAGE: Array<{ src: string; type: 'image' | 'video' }> = [
  { src: '/story-collage (1).jpg',  type: 'image' },
  { src: '/story-collage (2).jpg',  type: 'image' },
  { src: '/story-collage (3).jpg',  type: 'image' },
  { src: '/story-collage (4).jpg',  type: 'image' },
  { src: '/story-collage (5).jpg',  type: 'image' },
  { src: '/story-collage (6).jpg',  type: 'image' },
  { src: '/story-collage (7).png',  type: 'image' },
  { src: '/story-collage (8).jpg',  type: 'image' },
  { src: '/story-collage (9).png',  type: 'image' },
  { src: '/story-collage (1).mp4',  type: 'video' },
  { src: '/story-collage (2).mp4',  type: 'video' },
  { src: '/story-collage (3).mp4',  type: 'video' },
  { src: '/story-collage (4).mp4',  type: 'video' },
  { src: '/story-collage (6).mp4',  type: 'video' },
  { src: '/story-collage (8).mp4',  type: 'video' },
  { src: '/story-collage (9).mp4',  type: 'video' },
];

export const FALLBACK_FEATURED_PROJECTS = [
  {
    name: 'prototipo-ia-SEI',
    description: 'Interface futurista inspirada no JARVIS, combinando computação gráfica 3D reativa por áudio (Three.js), orquestrador de agentes com Function Calling e síntese neural de voz.',
    html_url: 'https://github.com/Ranyeri-Klennes/prototipo-ia-SEI',
    language: 'JavaScript',
    image: '/projects/prototipo-ia-jarvis.jpg',
    stargazers_count: 1,
    forks_count: 0,
    updated_at: '2026-03-24T00:00:00Z',
    created_at: '2026-03-20T00:00:00Z',
    topics: ['ai', 'agent', 'threejs', 'voice-synthesis', 'fastapi'],
    default_branch: 'main',
  },
  {
    name: 'uzzy',
    description: 'Plataforma de gestão e administração (Admin Dashboard) da rede de eletropostos UZZY Charger. Construído em Next.js (App Router) e TailwindCSS, com telemetria OCPP e split financeiro.',
    html_url: 'https://github.com/Ranyeri-Klennes/uzzy',
    language: 'TypeScript',
    image: '/projects/uzzy-1.jpg',
    images: [
      '/projects/uzzy-1.jpg',
      '/projects/uzzy-2.jpg',
      '/projects/uzzy-3.jpg'
    ],
    stargazers_count: 1,
    forks_count: 0,
    updated_at: '2026-03-24T00:00:00Z',
    created_at: '2026-03-15T00:00:00Z',
    topics: ['nextjs', 'typescript', 'tailwindcss', 'ev-charging', 'dashboard'],
    default_branch: 'main',
  },
  {
    name: 'meu-portfolio',
    description: 'Portfólio moderno e de alta performance desenvolvido em Next.js 16, TypeScript e TailwindCSS. Arquitetura espacial fluida, design responsivo, integração com APIs do GitHub e estética avançada.',
    html_url: 'https://github.com/Ranyeri-Klennes/meu-portfolio',
    language: 'TypeScript',
    image: '/projects/meu-portfolio.jpg',
    stargazers_count: 1,
    forks_count: 0,
    updated_at: '2026-03-22T22:01:26Z',
    created_at: '2026-03-20T18:28:44Z',
    topics: ['portfolio', 'nextjs', 'react19', 'typescript'],
    default_branch: 'main',
  },
  {
    name: 'App-Igreja-CENA',
    description: 'Plataforma e ecossistema web para a Igreja CENA, centralizando eventos, gestão de membros, dízimos, comunicados pastorais e transmissão de cultos com experiência mobile-first.',
    html_url: 'https://github.com/Ranyeri-Klennes/App-Igreja-CENA',
    language: 'TypeScript',
    image: '/projects/App-Igreja-CENA.jpg',
    stargazers_count: 1,
    forks_count: 0,
    updated_at: '2026-03-10T00:00:00Z',
    created_at: '2026-02-01T00:00:00Z',
    topics: ['nextjs', 'typescript', 'church-management', 'tailwind'],
    default_branch: 'main',
  },
];

